[project]
name = "notofu"
version = "0.1.0"
description = "Tools to avoid relying on trust on first use for SSH host keys"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "botocore",
    "requests",
]

[tool.uv]
python-preference = "system"
