[project]
name = "scripts"
version = "0.1.0"
description = "test scripts for notofu"
requires-python = ">=3.13"
dependencies = [
    "notofu.signer"
]

[tool.uv.sources]
"notofu-signer" = { workspace = true }